// client/src/components/Navbar.tsx
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";

export default function Navbar() {
  return (
    <motion.header
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      transition={{ type: "spring", stiffness: 100 }}
      className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-sm border-b"
    >
      <nav className="container mx-auto px-4 h-16 flex items-center justify-between">
        <motion.div
          className="flex items-center gap-2"
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        >
          <img 
            src="/logo.png" 
            alt="Colossus Logo" 
            className="h-8 w-auto"
            style={{ objectFit: 'contain' }}
          />
          <img 
            src="/nombre.png" 
            alt="Colossus" 
            className="h-6 w-auto"
            style={{ objectFit: 'contain' }}
          />
        </motion.div>

        <div className="hidden md:flex items-center gap-8">
          <a href="#services" className="text-foreground/80 hover:text-[#F15A24] transition-colors">
            Servicios
          </a>
          <a href="#team" className="text-foreground/80 hover:text-[#F15A24] transition-colors">
            Equipo
          </a>
          <a href="#contact" className="text-foreground/80 hover:text-[#F15A24] transition-colors">
            Contacto
          </a>
          <Button 
            className="bg-[#F15A24] hover:bg-[#F15A24]/90"
            onClick={() => document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' })}
          >
            Comienza Ahora
          </Button>
        </div>
      </nav>
    </motion.header>
  );
}

// client/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html'
})
export class NavbarComponent {
  navItems = [
    { label: 'Services', href: '#services' },
    { label: 'Team', href: '#team' },
    { label: 'Contact', href: '#contact' }
  ];
}

<mat-toolbar class="navbar">
  <div class="navbar-container">
    <a href="/" class="logo">
      <span class="logo-text">Colossus</span>
    </a>

    <nav class="nav-links">
      <a *ngFor="let item of navItems" 
         [href]="item.href"
         class="nav-link">
        {{item.label}}
      </a>
    </nav>

    <button mat-raised-button color="primary">Get Started</button>
  </div>
</mat-toolbar>

<style>
.navbar {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  background: hsl(var(--background) / 0.8);
  backdrop-filter: blur(10px);
  border-bottom: 1px solid hsl(var(--border));
}

.navbar-container {
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 1rem;
}

.logo {
  text-decoration: none;
  color: hsl(var(--foreground));
  
  .logo-text {
    font-size: 1.5rem;
    font-weight: 700;
  }
}

.nav-links {
  display: flex;
  gap: 2rem;

  @media (max-width: 768px) {
    display: none;
  }
}

.nav-link {
  color: hsl(var(--foreground));
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s;

  &:hover {
    color: hsl(var(--primary));
  }
}
</style>
